/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
import mikufan.cx.vocadbapiclient.model.ArchivedObjectVersionForApiContract;
import mikufan.cx.vocadbapiclient.model.EntryEditEvent;
import mikufan.cx.vocadbapiclient.model.EntryForApiContract;
import mikufan.cx.vocadbapiclient.model.UserForApiContract;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ActivityEntryForApiContract
 */
public class ActivityEntryForApiContractTest {
    private final ActivityEntryForApiContract model = new ActivityEntryForApiContract();

    /**
     * Model tests for ActivityEntryForApiContract
     */
    @Test
    public void testActivityEntryForApiContract() {
        // TODO: test ActivityEntryForApiContract
    }

    /**
     * Test the property 'archivedVersion'
     */
    @Test
    public void archivedVersionTest() {
        // TODO: test archivedVersion
    }

    /**
     * Test the property 'author'
     */
    @Test
    public void authorTest() {
        // TODO: test author
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'editEvent'
     */
    @Test
    public void editEventTest() {
        // TODO: test editEvent
    }

    /**
     * Test the property 'entry'
     */
    @Test
    public void entryTest() {
        // TODO: test entry
    }

}
