/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import mikufan.cx.vocadbapiclient.model.AlbumDiscPropertiesContract;
import mikufan.cx.vocadbapiclient.model.AlbumIdentifierContract;
import mikufan.cx.vocadbapiclient.model.ArtistForAlbumForApiContract;
import mikufan.cx.vocadbapiclient.model.ContentLanguageSelection;
import mikufan.cx.vocadbapiclient.model.DiscType;
import mikufan.cx.vocadbapiclient.model.EntryStatus;
import mikufan.cx.vocadbapiclient.model.EntryThumbForApiContract;
import mikufan.cx.vocadbapiclient.model.LocalizedStringContract;
import mikufan.cx.vocadbapiclient.model.OptionalDateTimeContract;
import mikufan.cx.vocadbapiclient.model.PVContract;
import mikufan.cx.vocadbapiclient.model.ReleaseEventForApiContract;
import mikufan.cx.vocadbapiclient.model.SongInAlbumForApiContract;
import mikufan.cx.vocadbapiclient.model.TagUsageForApiContract;
import mikufan.cx.vocadbapiclient.model.WebLinkForApiContract;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AlbumForApiContract
 */
public class AlbumForApiContractTest {
    private final AlbumForApiContract model = new AlbumForApiContract();

    /**
     * Model tests for AlbumForApiContract
     */
    @Test
    public void testAlbumForApiContract() {
        // TODO: test AlbumForApiContract
    }

    /**
     * Test the property 'additionalNames'
     */
    @Test
    public void additionalNamesTest() {
        // TODO: test additionalNames
    }

    /**
     * Test the property 'artists'
     */
    @Test
    public void artistsTest() {
        // TODO: test artists
    }

    /**
     * Test the property 'artistString'
     */
    @Test
    public void artistStringTest() {
        // TODO: test artistString
    }

    /**
     * Test the property 'barcode'
     */
    @Test
    public void barcodeTest() {
        // TODO: test barcode
    }

    /**
     * Test the property 'catalogNumber'
     */
    @Test
    public void catalogNumberTest() {
        // TODO: test catalogNumber
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'defaultName'
     */
    @Test
    public void defaultNameTest() {
        // TODO: test defaultName
    }

    /**
     * Test the property 'defaultNameLanguage'
     */
    @Test
    public void defaultNameLanguageTest() {
        // TODO: test defaultNameLanguage
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'discs'
     */
    @Test
    public void discsTest() {
        // TODO: test discs
    }

    /**
     * Test the property 'discType'
     */
    @Test
    public void discTypeTest() {
        // TODO: test discType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'identifiers'
     */
    @Test
    public void identifiersTest() {
        // TODO: test identifiers
    }

    /**
     * Test the property 'mainPicture'
     */
    @Test
    public void mainPictureTest() {
        // TODO: test mainPicture
    }

    /**
     * Test the property 'mergedTo'
     */
    @Test
    public void mergedToTest() {
        // TODO: test mergedTo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'names'
     */
    @Test
    public void namesTest() {
        // TODO: test names
    }

    /**
     * Test the property 'pvs'
     */
    @Test
    public void pvsTest() {
        // TODO: test pvs
    }

    /**
     * Test the property 'ratingAverage'
     */
    @Test
    public void ratingAverageTest() {
        // TODO: test ratingAverage
    }

    /**
     * Test the property 'ratingCount'
     */
    @Test
    public void ratingCountTest() {
        // TODO: test ratingCount
    }

    /**
     * Test the property 'releaseDate'
     */
    @Test
    public void releaseDateTest() {
        // TODO: test releaseDate
    }

    /**
     * Test the property 'releaseEvent'
     */
    @Test
    public void releaseEventTest() {
        // TODO: test releaseEvent
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'tracks'
     */
    @Test
    public void tracksTest() {
        // TODO: test tracks
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'webLinks'
     */
    @Test
    public void webLinksTest() {
        // TODO: test webLinks
    }

}
