/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for EnglishTranslatedStringContract
 */
public class EnglishTranslatedStringContractTest {
    private final EnglishTranslatedStringContract model = new EnglishTranslatedStringContract();

    /**
     * Model tests for EnglishTranslatedStringContract
     */
    @Test
    public void testEnglishTranslatedStringContract() {
        // TODO: test EnglishTranslatedStringContract
    }

    /**
     * Test the property 'english'
     */
    @Test
    public void englishTest() {
        // TODO: test english
    }

    /**
     * Test the property 'original'
     */
    @Test
    public void originalTest() {
        // TODO: test original
    }

}
