/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import mikufan.cx.vocadbapiclient.model.SongForApiContract;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RelatedSongsContract
 */
public class RelatedSongsContractTest {
    private final RelatedSongsContract model = new RelatedSongsContract();

    /**
     * Model tests for RelatedSongsContract
     */
    @Test
    public void testRelatedSongsContract() {
        // TODO: test RelatedSongsContract
    }

    /**
     * Test the property 'artistMatches'
     */
    @Test
    public void artistMatchesTest() {
        // TODO: test artistMatches
    }

    /**
     * Test the property 'likeMatches'
     */
    @Test
    public void likeMatchesTest() {
        // TODO: test likeMatches
    }

    /**
     * Test the property 'tagMatches'
     */
    @Test
    public void tagMatchesTest() {
        // TODO: test tagMatches
    }

}
