/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import mikufan.cx.vocadbapiclient.model.ReleaseEventForApiContract;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ReleaseEventForApiContractPartialFindResult
 */
public class ReleaseEventForApiContractPartialFindResultTest {
    private final ReleaseEventForApiContractPartialFindResult model = new ReleaseEventForApiContractPartialFindResult();

    /**
     * Model tests for ReleaseEventForApiContractPartialFindResult
     */
    @Test
    public void testReleaseEventForApiContractPartialFindResult() {
        // TODO: test ReleaseEventForApiContractPartialFindResult
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'term'
     */
    @Test
    public void termTest() {
        // TODO: test term
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    public void totalCountTest() {
        // TODO: test totalCount
    }

}
