/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
import mikufan.cx.vocadbapiclient.model.EntryStatus;
import mikufan.cx.vocadbapiclient.model.EventCategory;
import mikufan.cx.vocadbapiclient.model.ReleaseEventSeriesContract;
import mikufan.cx.vocadbapiclient.model.SongListBaseContract;
import mikufan.cx.vocadbapiclient.model.VenueContract;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ReleaseEventContract
 */
public class ReleaseEventContractTest {
    private final ReleaseEventContract model = new ReleaseEventContract();

    /**
     * Model tests for ReleaseEventContract
     */
    @Test
    public void testReleaseEventContract() {
        // TODO: test ReleaseEventContract
    }

    /**
     * Test the property 'additionalNames'
     */
    @Test
    public void additionalNamesTest() {
        // TODO: test additionalNames
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'customName'
     */
    @Test
    public void customNameTest() {
        // TODO: test customName
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'hasVenueOrVenueName'
     */
    @Test
    public void hasVenueOrVenueNameTest() {
        // TODO: test hasVenueOrVenueName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'inheritedCategory'
     */
    @Test
    public void inheritedCategoryTest() {
        // TODO: test inheritedCategory
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pictureMime'
     */
    @Test
    public void pictureMimeTest() {
        // TODO: test pictureMime
    }

    /**
     * Test the property 'series'
     */
    @Test
    public void seriesTest() {
        // TODO: test series
    }

    /**
     * Test the property 'songList'
     */
    @Test
    public void songListTest() {
        // TODO: test songList
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'urlSlug'
     */
    @Test
    public void urlSlugTest() {
        // TODO: test urlSlug
    }

    /**
     * Test the property 'venue'
     */
    @Test
    public void venueTest() {
        // TODO: test venue
    }

    /**
     * Test the property 'venueName'
     */
    @Test
    public void venueNameTest() {
        // TODO: test venueName
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
