/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import mikufan.cx.vocadbapiclient.model.SongForApiContract;
import mikufan.cx.vocadbapiclient.model.SongVoteRating;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for SongInAlbumForApiContract
 */
public class SongInAlbumForApiContractTest {
    private final SongInAlbumForApiContract model = new SongInAlbumForApiContract();

    /**
     * Model tests for SongInAlbumForApiContract
     */
    @Test
    public void testSongInAlbumForApiContract() {
        // TODO: test SongInAlbumForApiContract
    }

    /**
     * Test the property 'discNumber'
     */
    @Test
    public void discNumberTest() {
        // TODO: test discNumber
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'song'
     */
    @Test
    public void songTest() {
        // TODO: test song
    }

    /**
     * Test the property 'trackNumber'
     */
    @Test
    public void trackNumberTest() {
        // TODO: test trackNumber
    }

    /**
     * Test the property 'computedCultureCodes'
     */
    @Test
    public void computedCultureCodesTest() {
        // TODO: test computedCultureCodes
    }

}
