/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TopSongsDateFilterType
 */
public class TopSongsDateFilterTypeTest {
    /**
     * Model tests for TopSongsDateFilterType
     */
    @Test
    public void testTopSongsDateFilterType() {
        // TODO: test TopSongsDateFilterType
    }

}
