/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.AlbumForApiContract;
import cx.mikufan.vocadbapiclient.model.MediaType;
import cx.mikufan.vocadbapiclient.model.PurchaseStatus;
import cx.mikufan.vocadbapiclient.model.UserForApiContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AlbumForUserForApiContract
 */
public class AlbumForUserForApiContractTest {
    private final AlbumForUserForApiContract model = new AlbumForUserForApiContract();

    /**
     * Model tests for AlbumForUserForApiContract
     */
    @Test
    public void testAlbumForUserForApiContract() {
        // TODO: test AlbumForUserForApiContract
    }

    /**
     * Test the property 'album'
     */
    @Test
    public void albumTest() {
        // TODO: test album
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    public void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'purchaseStatus'
     */
    @Test
    public void purchaseStatusTest() {
        // TODO: test purchaseStatus
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
