/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.DiscType;
import cx.mikufan.vocadbapiclient.model.EntryStatus;
import cx.mikufan.vocadbapiclient.model.OptionalDateTimeContract;
import cx.mikufan.vocadbapiclient.model.ReleaseEventForApiContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AlbumContract
 */
public class AlbumContractTest {
    private final AlbumContract model = new AlbumContract();

    /**
     * Model tests for AlbumContract
     */
    @Test
    public void testAlbumContract() {
        // TODO: test AlbumContract
    }

    /**
     * Test the property 'additionalNames'
     */
    @Test
    public void additionalNamesTest() {
        // TODO: test additionalNames
    }

    /**
     * Test the property 'artistString'
     */
    @Test
    public void artistStringTest() {
        // TODO: test artistString
    }

    /**
     * Test the property 'coverPictureMime'
     */
    @Test
    public void coverPictureMimeTest() {
        // TODO: test coverPictureMime
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'discType'
     */
    @Test
    public void discTypeTest() {
        // TODO: test discType
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ratingAverage'
     */
    @Test
    public void ratingAverageTest() {
        // TODO: test ratingAverage
    }

    /**
     * Test the property 'ratingCount'
     */
    @Test
    public void ratingCountTest() {
        // TODO: test ratingCount
    }

    /**
     * Test the property 'releaseDate'
     */
    @Test
    public void releaseDateTest() {
        // TODO: test releaseDate
    }

    /**
     * Test the property 'releaseEvent'
     */
    @Test
    public void releaseEventTest() {
        // TODO: test releaseEvent
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
