/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.ArtistContract;
import cx.mikufan.vocadbapiclient.model.ArtistLinkType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArtistForArtistForApiContract
 */
public class ArtistForArtistForApiContractTest {
    private final ArtistForArtistForApiContract model = new ArtistForArtistForApiContract();

    /**
     * Model tests for ArtistForArtistForApiContract
     */
    @Test
    public void testArtistForArtistForApiContract() {
        // TODO: test ArtistForArtistForApiContract
    }

    /**
     * Test the property 'artist'
     */
    @Test
    public void artistTest() {
        // TODO: test artist
    }

    /**
     * Test the property 'linkType'
     */
    @Test
    public void linkTypeTest() {
        // TODO: test linkType
    }

}
