/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.ArtistCategories;
import cx.mikufan.vocadbapiclient.model.ArtistContract;
import cx.mikufan.vocadbapiclient.model.ArtistRoles;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArtistForSongContract
 */
public class ArtistForSongContractTest {
    private final ArtistForSongContract model = new ArtistForSongContract();

    /**
     * Model tests for ArtistForSongContract
     */
    @Test
    public void testArtistForSongContract() {
        // TODO: test ArtistForSongContract
    }

    /**
     * Test the property 'artist'
     */
    @Test
    public void artistTest() {
        // TODO: test artist
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'effectiveRoles'
     */
    @Test
    public void effectiveRolesTest() {
        // TODO: test effectiveRoles
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isCustomName'
     */
    @Test
    public void isCustomNameTest() {
        // TODO: test isCustomName
    }

    /**
     * Test the property 'isSupport'
     */
    @Test
    public void isSupportTest() {
        // TODO: test isSupport
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'roles'
     */
    @Test
    public void rolesTest() {
        // TODO: test roles
    }

}
