/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.AlbumForApiContract;
import cx.mikufan.vocadbapiclient.model.ReleaseEventForApiContract;
import cx.mikufan.vocadbapiclient.model.SongForApiContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ArtistRelationsForApi
 */
public class ArtistRelationsForApiTest {
    private final ArtistRelationsForApi model = new ArtistRelationsForApi();

    /**
     * Model tests for ArtistRelationsForApi
     */
    @Test
    public void testArtistRelationsForApi() {
        // TODO: test ArtistRelationsForApi
    }

    /**
     * Test the property 'latestAlbums'
     */
    @Test
    public void latestAlbumsTest() {
        // TODO: test latestAlbums
    }

    /**
     * Test the property 'latestEvents'
     */
    @Test
    public void latestEventsTest() {
        // TODO: test latestEvents
    }

    /**
     * Test the property 'latestSongs'
     */
    @Test
    public void latestSongsTest() {
        // TODO: test latestSongs
    }

    /**
     * Test the property 'popularAlbums'
     */
    @Test
    public void popularAlbumsTest() {
        // TODO: test popularAlbums
    }

    /**
     * Test the property 'popularSongs'
     */
    @Test
    public void popularSongsTest() {
        // TODO: test popularSongs
    }

}
