/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OptionalGeoPointContract
 */
public class OptionalGeoPointContractTest {
    private final OptionalGeoPointContract model = new OptionalGeoPointContract();

    /**
     * Model tests for OptionalGeoPointContract
     */
    @Test
    public void testOptionalGeoPointContract() {
        // TODO: test OptionalGeoPointContract
    }

    /**
     * Test the property 'formatted'
     */
    @Test
    public void formattedTest() {
        // TODO: test formatted
    }

    /**
     * Test the property 'hasValue'
     */
    @Test
    public void hasValueTest() {
        // TODO: test hasValue
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

}
