/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.ContentLanguageSelection;
import cx.mikufan.vocadbapiclient.model.EnglishTranslatedStringContract;
import cx.mikufan.vocadbapiclient.model.EntryStatus;
import cx.mikufan.vocadbapiclient.model.EntryThumbForApiContract;
import cx.mikufan.vocadbapiclient.model.LocalizedStringWithIdContract;
import cx.mikufan.vocadbapiclient.model.TagBaseContract;
import cx.mikufan.vocadbapiclient.model.WebLinkForApiContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TagForApiContract
 */
public class TagForApiContractTest {
    private final TagForApiContract model = new TagForApiContract();

    /**
     * Model tests for TagForApiContract
     */
    @Test
    public void testTagForApiContract() {
        // TODO: test TagForApiContract
    }

    /**
     * Test the property 'additionalNames'
     */
    @Test
    public void additionalNamesTest() {
        // TODO: test additionalNames
    }

    /**
     * Test the property 'aliasedTo'
     */
    @Test
    public void aliasedToTest() {
        // TODO: test aliasedTo
    }

    /**
     * Test the property 'categoryName'
     */
    @Test
    public void categoryNameTest() {
        // TODO: test categoryName
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'defaultNameLanguage'
     */
    @Test
    public void defaultNameLanguageTest() {
        // TODO: test defaultNameLanguage
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'mainPicture'
     */
    @Test
    public void mainPictureTest() {
        // TODO: test mainPicture
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'names'
     */
    @Test
    public void namesTest() {
        // TODO: test names
    }

    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }

    /**
     * Test the property 'relatedTags'
     */
    @Test
    public void relatedTagsTest() {
        // TODO: test relatedTags
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'targets'
     */
    @Test
    public void targetsTest() {
        // TODO: test targets
    }

    /**
     * Test the property 'translatedDescription'
     */
    @Test
    public void translatedDescriptionTest() {
        // TODO: test translatedDescription
    }

    /**
     * Test the property 'urlSlug'
     */
    @Test
    public void urlSlugTest() {
        // TODO: test urlSlug
    }

    /**
     * Test the property 'usageCount'
     */
    @Test
    public void usageCountTest() {
        // TODO: test usageCount
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'webLinks'
     */
    @Test
    public void webLinksTest() {
        // TODO: test webLinks
    }

}
