io:
  input-project-directory:
  output-project-directory:
  model-relative-path:

config:
  dry-run: false
  multi-enums-class-template: multi-enums.java.template
  package-capture-regex: package ((\.|\w)+)
  enum-capture-regex: ([A-Z]+\("\w+"\))
  api-api-fix:
    ignore-directory: bin, \.\w+, gradle


logging:
  level:
    mikufan:
      cx: debug