/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.api;

import cx.mikufan.vocadbapiclient.model.ContentLanguagePreference;
import cx.mikufan.vocadbapiclient.model.EntryForApiContractPartialFindResult;
import cx.mikufan.vocadbapiclient.model.EntryOptionalFields;
import cx.mikufan.vocadbapiclient.model.EntrySortRule;
import cx.mikufan.vocadbapiclient.model.EntryStatus;
import cx.mikufan.vocadbapiclient.model.EntryTypes;
import cx.mikufan.vocadbapiclient.model.NameMatchMode;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntryApiApi
 */
@Ignore
public class EntryApiApiTest {

    private final EntryApiApi api = new EntryApiApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEntriesGetTest() {
        String query = null;
        List<String> tagName = null;
        List<Integer> tagId = null;
        Boolean childTags = null;
        EntryTypes entryTypes = null;
        EntryStatus status = null;
        Integer start = null;
        Integer maxResults = null;
        Boolean getTotalCount = null;
        EntrySortRule sort = null;
        NameMatchMode nameMatchMode = null;
        EntryOptionalFields fields = null;
        ContentLanguagePreference lang = null;
        EntryForApiContractPartialFindResult response = api.apiEntriesGet(query, tagName, tagId, childTags, entryTypes, status, start, maxResults, getTotalCount, sort, nameMatchMode, fields, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEntriesNamesGetTest() {
        String query = null;
        NameMatchMode nameMatchMode = null;
        Integer maxResults = null;
        List<String> response = api.apiEntriesNamesGet(query, nameMatchMode, maxResults);

        // TODO: test validations
    }
    
}
