/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
import mikufan.cx.vocadbapiclient.model.ArchivedObjectVersionForApiContract;
import mikufan.cx.vocadbapiclient.model.EntryEditEvent;
import mikufan.cx.vocadbapiclient.model.EntryForApiContract;
import mikufan.cx.vocadbapiclient.model.UserForApiContract;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ActivityEntryForApiContract
 */
@JsonPropertyOrder({
  ActivityEntryForApiContract.JSON_PROPERTY_ARCHIVED_VERSION,
  ActivityEntryForApiContract.JSON_PROPERTY_AUTHOR,
  ActivityEntryForApiContract.JSON_PROPERTY_CREATE_DATE,
  ActivityEntryForApiContract.JSON_PROPERTY_EDIT_EVENT,
  ActivityEntryForApiContract.JSON_PROPERTY_ENTRY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-26T07:29:58.607748373Z[Etc/UTC]")
public class ActivityEntryForApiContract {
  public static final String JSON_PROPERTY_ARCHIVED_VERSION = "archivedVersion";
  private ArchivedObjectVersionForApiContract archivedVersion;

  public static final String JSON_PROPERTY_AUTHOR = "author";
  private UserForApiContract author;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  private LocalDateTime createDate;

  public static final String JSON_PROPERTY_EDIT_EVENT = "editEvent";
  private EntryEditEvent editEvent;

  public static final String JSON_PROPERTY_ENTRY = "entry";
  private EntryForApiContract entry;

  public ActivityEntryForApiContract() {
  }

  public ActivityEntryForApiContract archivedVersion(ArchivedObjectVersionForApiContract archivedVersion) {
    
    this.archivedVersion = archivedVersion;
    return this;
  }

   /**
   * Get archivedVersion
   * @return archivedVersion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARCHIVED_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ArchivedObjectVersionForApiContract getArchivedVersion() {
    return archivedVersion;
  }


  @JsonProperty(JSON_PROPERTY_ARCHIVED_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchivedVersion(ArchivedObjectVersionForApiContract archivedVersion) {
    this.archivedVersion = archivedVersion;
  }


  public ActivityEntryForApiContract author(UserForApiContract author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserForApiContract getAuthor() {
    return author;
  }


  @JsonProperty(JSON_PROPERTY_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthor(UserForApiContract author) {
    this.author = author;
  }


  public ActivityEntryForApiContract createDate(LocalDateTime createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getCreateDate() {
    return createDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateDate(LocalDateTime createDate) {
    this.createDate = createDate;
  }


  public ActivityEntryForApiContract editEvent(EntryEditEvent editEvent) {
    
    this.editEvent = editEvent;
    return this;
  }

   /**
   * Get editEvent
   * @return editEvent
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EDIT_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryEditEvent getEditEvent() {
    return editEvent;
  }


  @JsonProperty(JSON_PROPERTY_EDIT_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEditEvent(EntryEditEvent editEvent) {
    this.editEvent = editEvent;
  }


  public ActivityEntryForApiContract entry(EntryForApiContract entry) {
    
    this.entry = entry;
    return this;
  }

   /**
   * Get entry
   * @return entry
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryForApiContract getEntry() {
    return entry;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntry(EntryForApiContract entry) {
    this.entry = entry;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityEntryForApiContract activityEntryForApiContract = (ActivityEntryForApiContract) o;
    return Objects.equals(this.archivedVersion, activityEntryForApiContract.archivedVersion) &&
        Objects.equals(this.author, activityEntryForApiContract.author) &&
        Objects.equals(this.createDate, activityEntryForApiContract.createDate) &&
        Objects.equals(this.editEvent, activityEntryForApiContract.editEvent) &&
        Objects.equals(this.entry, activityEntryForApiContract.entry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedVersion, author, createDate, editEvent, entry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivityEntryForApiContract {\n");
    sb.append("    archivedVersion: ").append(toIndentedString(archivedVersion)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    editEvent: ").append(toIndentedString(editEvent)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

