/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ArtistType
 */
public enum ArtistType {
  
  UNKNOWN("Unknown"),
  
  CIRCLE("Circle"),
  
  LABEL("Label"),
  
  PRODUCER("Producer"),
  
  ANIMATOR("Animator"),
  
  ILLUSTRATOR("Illustrator"),
  
  LYRICIST("Lyricist"),
  
  VOCALOID("Vocaloid"),
  
  UTAU("UTAU"),
  
  CEVIO("CeVIO"),
  
  OTHERVOICESYNTHESIZER("OtherVoiceSynthesizer"),
  
  OTHERVOCALIST("OtherVocalist"),
  
  OTHERGROUP("OtherGroup"),
  
  OTHERINDIVIDUAL("OtherIndividual"),
  
  UTAITE("Utaite"),
  
  BAND("Band"),
  
  VOCALIST("Vocalist"),
  
  CHARACTER("Character"),
  
  SYNTHESIZERV("SynthesizerV"),
  
  COVERARTIST("CoverArtist");

  private String value;

  ArtistType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ArtistType fromValue(String value) {
    for (ArtistType b : ArtistType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

