/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import mikufan.cx.vocadbapiclient.model.UserForApiContract;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * DiscussionFolderContract
 */
@JsonPropertyOrder({
  DiscussionFolderContract.JSON_PROPERTY_DESCRIPTION,
  DiscussionFolderContract.JSON_PROPERTY_ID,
  DiscussionFolderContract.JSON_PROPERTY_LAST_TOPIC_AUTHOR,
  DiscussionFolderContract.JSON_PROPERTY_LAST_TOPIC_DATE,
  DiscussionFolderContract.JSON_PROPERTY_NAME,
  DiscussionFolderContract.JSON_PROPERTY_TOPIC_COUNT
})
@JsonTypeName("DiscussionFolderContract")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-23T13:02:48.301797700-04:00[America/New_York]")
public class DiscussionFolderContract {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_LAST_TOPIC_AUTHOR = "lastTopicAuthor";
  private UserForApiContract lastTopicAuthor;

  public static final String JSON_PROPERTY_LAST_TOPIC_DATE = "lastTopicDate";
  private LocalDateTime lastTopicDate;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_TOPIC_COUNT = "topicCount";
  private Integer topicCount;


  public DiscussionFolderContract description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public DiscussionFolderContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public DiscussionFolderContract lastTopicAuthor(UserForApiContract lastTopicAuthor) {
    
    this.lastTopicAuthor = lastTopicAuthor;
    return this;
  }

   /**
   * Get lastTopicAuthor
   * @return lastTopicAuthor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_TOPIC_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UserForApiContract getLastTopicAuthor() {
    return lastTopicAuthor;
  }


  @JsonProperty(JSON_PROPERTY_LAST_TOPIC_AUTHOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastTopicAuthor(UserForApiContract lastTopicAuthor) {
    this.lastTopicAuthor = lastTopicAuthor;
  }


  public DiscussionFolderContract lastTopicDate(LocalDateTime lastTopicDate) {
    
    this.lastTopicDate = lastTopicDate;
    return this;
  }

   /**
   * Get lastTopicDate
   * @return lastTopicDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_TOPIC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getLastTopicDate() {
    return lastTopicDate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_TOPIC_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastTopicDate(LocalDateTime lastTopicDate) {
    this.lastTopicDate = lastTopicDate;
  }


  public DiscussionFolderContract name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public DiscussionFolderContract topicCount(Integer topicCount) {
    
    this.topicCount = topicCount;
    return this;
  }

   /**
   * Get topicCount
   * @return topicCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TOPIC_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTopicCount() {
    return topicCount;
  }


  @JsonProperty(JSON_PROPERTY_TOPIC_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopicCount(Integer topicCount) {
    this.topicCount = topicCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscussionFolderContract discussionFolderContract = (DiscussionFolderContract) o;
    return Objects.equals(this.description, discussionFolderContract.description) &&
        Objects.equals(this.id, discussionFolderContract.id) &&
        Objects.equals(this.lastTopicAuthor, discussionFolderContract.lastTopicAuthor) &&
        Objects.equals(this.lastTopicDate, discussionFolderContract.lastTopicDate) &&
        Objects.equals(this.name, discussionFolderContract.name) &&
        Objects.equals(this.topicCount, discussionFolderContract.topicCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, lastTopicAuthor, lastTopicDate, name, topicCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscussionFolderContract {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastTopicAuthor: ").append(toIndentedString(lastTopicAuthor)).append("\n");
    sb.append("    lastTopicDate: ").append(toIndentedString(lastTopicDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    topicCount: ").append(toIndentedString(topicCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

