/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import mikufan.cx.vocadbapiclient.model.ArtistForEventContract;
import mikufan.cx.vocadbapiclient.model.EntryStatus;
import mikufan.cx.vocadbapiclient.model.EntryThumbForApiContract;
import mikufan.cx.vocadbapiclient.model.EventCategory;
import mikufan.cx.vocadbapiclient.model.LocalizedStringContract;
import mikufan.cx.vocadbapiclient.model.ReleaseEventSeriesContract;
import mikufan.cx.vocadbapiclient.model.SongListBaseContract;
import mikufan.cx.vocadbapiclient.model.TagUsageForApiContract;
import mikufan.cx.vocadbapiclient.model.VenueForApiContract;
import mikufan.cx.vocadbapiclient.model.WebLinkForApiContract;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ReleaseEventForApiContract
 */
@JsonPropertyOrder({
  ReleaseEventForApiContract.JSON_PROPERTY_ADDITIONAL_NAMES,
  ReleaseEventForApiContract.JSON_PROPERTY_ARTISTS,
  ReleaseEventForApiContract.JSON_PROPERTY_CATEGORY,
  ReleaseEventForApiContract.JSON_PROPERTY_DATE,
  ReleaseEventForApiContract.JSON_PROPERTY_DESCRIPTION,
  ReleaseEventForApiContract.JSON_PROPERTY_END_DATE,
  ReleaseEventForApiContract.JSON_PROPERTY_ID,
  ReleaseEventForApiContract.JSON_PROPERTY_MAIN_PICTURE,
  ReleaseEventForApiContract.JSON_PROPERTY_NAME,
  ReleaseEventForApiContract.JSON_PROPERTY_NAMES,
  ReleaseEventForApiContract.JSON_PROPERTY_SERIES,
  ReleaseEventForApiContract.JSON_PROPERTY_SERIES_ID,
  ReleaseEventForApiContract.JSON_PROPERTY_SERIES_NUMBER,
  ReleaseEventForApiContract.JSON_PROPERTY_SERIES_SUFFIX,
  ReleaseEventForApiContract.JSON_PROPERTY_SONG_LIST,
  ReleaseEventForApiContract.JSON_PROPERTY_STATUS,
  ReleaseEventForApiContract.JSON_PROPERTY_TAGS,
  ReleaseEventForApiContract.JSON_PROPERTY_URL_SLUG,
  ReleaseEventForApiContract.JSON_PROPERTY_VENUE,
  ReleaseEventForApiContract.JSON_PROPERTY_VENUE_NAME,
  ReleaseEventForApiContract.JSON_PROPERTY_VERSION,
  ReleaseEventForApiContract.JSON_PROPERTY_WEB_LINKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-02T20:16:06.008977Z[Etc/UTC]")
public class ReleaseEventForApiContract {
  public static final String JSON_PROPERTY_ADDITIONAL_NAMES = "additionalNames";
  private String additionalNames;

  public static final String JSON_PROPERTY_ARTISTS = "artists";
  private List<ArtistForEventContract> artists = null;

  public static final String JSON_PROPERTY_CATEGORY = "category";
  private EventCategory category;

  public static final String JSON_PROPERTY_DATE = "date";
  private LocalDateTime date;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private LocalDateTime endDate;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_MAIN_PICTURE = "mainPicture";
  private EntryThumbForApiContract mainPicture;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NAMES = "names";
  private List<LocalizedStringContract> names = null;

  public static final String JSON_PROPERTY_SERIES = "series";
  private ReleaseEventSeriesContract series;

  public static final String JSON_PROPERTY_SERIES_ID = "seriesId";
  private Integer seriesId;

  public static final String JSON_PROPERTY_SERIES_NUMBER = "seriesNumber";
  private Integer seriesNumber;

  public static final String JSON_PROPERTY_SERIES_SUFFIX = "seriesSuffix";
  private String seriesSuffix;

  public static final String JSON_PROPERTY_SONG_LIST = "songList";
  private SongListBaseContract songList;

  public static final String JSON_PROPERTY_STATUS = "status";
  private EntryStatus status;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<TagUsageForApiContract> tags = null;

  public static final String JSON_PROPERTY_URL_SLUG = "urlSlug";
  private String urlSlug;

  public static final String JSON_PROPERTY_VENUE = "venue";
  private VenueForApiContract venue;

  public static final String JSON_PROPERTY_VENUE_NAME = "venueName";
  private String venueName;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;

  public static final String JSON_PROPERTY_WEB_LINKS = "webLinks";
  private List<WebLinkForApiContract> webLinks = null;

  public ReleaseEventForApiContract() {
  }

  public ReleaseEventForApiContract additionalNames(String additionalNames) {
    
    this.additionalNames = additionalNames;
    return this;
  }

   /**
   * Get additionalNames
   * @return additionalNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalNames() {
    return additionalNames;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalNames(String additionalNames) {
    this.additionalNames = additionalNames;
  }


  public ReleaseEventForApiContract artists(List<ArtistForEventContract> artists) {
    
    this.artists = artists;
    return this;
  }

  public ReleaseEventForApiContract addArtistsItem(ArtistForEventContract artistsItem) {
    if (this.artists == null) {
      this.artists = new ArrayList<>();
    }
    this.artists.add(artistsItem);
    return this;
  }

   /**
   * Get artists
   * @return artists
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ARTISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ArtistForEventContract> getArtists() {
    return artists;
  }


  @JsonProperty(JSON_PROPERTY_ARTISTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArtists(List<ArtistForEventContract> artists) {
    this.artists = artists;
  }


  public ReleaseEventForApiContract category(EventCategory category) {
    
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventCategory getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(EventCategory category) {
    this.category = category;
  }


  public ReleaseEventForApiContract date(LocalDateTime date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(LocalDateTime date) {
    this.date = date;
  }


  public ReleaseEventForApiContract description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ReleaseEventForApiContract endDate(LocalDateTime endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getEndDate() {
    return endDate;
  }


  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(LocalDateTime endDate) {
    this.endDate = endDate;
  }


  public ReleaseEventForApiContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public ReleaseEventForApiContract mainPicture(EntryThumbForApiContract mainPicture) {
    
    this.mainPicture = mainPicture;
    return this;
  }

   /**
   * Get mainPicture
   * @return mainPicture
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MAIN_PICTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryThumbForApiContract getMainPicture() {
    return mainPicture;
  }


  @JsonProperty(JSON_PROPERTY_MAIN_PICTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMainPicture(EntryThumbForApiContract mainPicture) {
    this.mainPicture = mainPicture;
  }


  public ReleaseEventForApiContract name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ReleaseEventForApiContract names(List<LocalizedStringContract> names) {
    
    this.names = names;
    return this;
  }

  public ReleaseEventForApiContract addNamesItem(LocalizedStringContract namesItem) {
    if (this.names == null) {
      this.names = new ArrayList<>();
    }
    this.names.add(namesItem);
    return this;
  }

   /**
   * Get names
   * @return names
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LocalizedStringContract> getNames() {
    return names;
  }


  @JsonProperty(JSON_PROPERTY_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNames(List<LocalizedStringContract> names) {
    this.names = names;
  }


  public ReleaseEventForApiContract series(ReleaseEventSeriesContract series) {
    
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReleaseEventSeriesContract getSeries() {
    return series;
  }


  @JsonProperty(JSON_PROPERTY_SERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeries(ReleaseEventSeriesContract series) {
    this.series = series;
  }


  public ReleaseEventForApiContract seriesId(Integer seriesId) {
    
    this.seriesId = seriesId;
    return this;
  }

   /**
   * Get seriesId
   * @return seriesId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeriesId() {
    return seriesId;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesId(Integer seriesId) {
    this.seriesId = seriesId;
  }


  public ReleaseEventForApiContract seriesNumber(Integer seriesNumber) {
    
    this.seriesNumber = seriesNumber;
    return this;
  }

   /**
   * Get seriesNumber
   * @return seriesNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSeriesNumber() {
    return seriesNumber;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesNumber(Integer seriesNumber) {
    this.seriesNumber = seriesNumber;
  }


  public ReleaseEventForApiContract seriesSuffix(String seriesSuffix) {
    
    this.seriesSuffix = seriesSuffix;
    return this;
  }

   /**
   * Get seriesSuffix
   * @return seriesSuffix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSeriesSuffix() {
    return seriesSuffix;
  }


  @JsonProperty(JSON_PROPERTY_SERIES_SUFFIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeriesSuffix(String seriesSuffix) {
    this.seriesSuffix = seriesSuffix;
  }


  public ReleaseEventForApiContract songList(SongListBaseContract songList) {
    
    this.songList = songList;
    return this;
  }

   /**
   * Get songList
   * @return songList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SONG_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SongListBaseContract getSongList() {
    return songList;
  }


  @JsonProperty(JSON_PROPERTY_SONG_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSongList(SongListBaseContract songList) {
    this.songList = songList;
  }


  public ReleaseEventForApiContract status(EntryStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(EntryStatus status) {
    this.status = status;
  }


  public ReleaseEventForApiContract tags(List<TagUsageForApiContract> tags) {
    
    this.tags = tags;
    return this;
  }

  public ReleaseEventForApiContract addTagsItem(TagUsageForApiContract tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TagUsageForApiContract> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<TagUsageForApiContract> tags) {
    this.tags = tags;
  }


  public ReleaseEventForApiContract urlSlug(String urlSlug) {
    
    this.urlSlug = urlSlug;
    return this;
  }

   /**
   * Get urlSlug
   * @return urlSlug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrlSlug() {
    return urlSlug;
  }


  @JsonProperty(JSON_PROPERTY_URL_SLUG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrlSlug(String urlSlug) {
    this.urlSlug = urlSlug;
  }


  public ReleaseEventForApiContract venue(VenueForApiContract venue) {
    
    this.venue = venue;
    return this;
  }

   /**
   * Get venue
   * @return venue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VenueForApiContract getVenue() {
    return venue;
  }


  @JsonProperty(JSON_PROPERTY_VENUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVenue(VenueForApiContract venue) {
    this.venue = venue;
  }


  public ReleaseEventForApiContract venueName(String venueName) {
    
    this.venueName = venueName;
    return this;
  }

   /**
   * Get venueName
   * @return venueName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VENUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVenueName() {
    return venueName;
  }


  @JsonProperty(JSON_PROPERTY_VENUE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVenueName(String venueName) {
    this.venueName = venueName;
  }


  public ReleaseEventForApiContract version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(Integer version) {
    this.version = version;
  }


  public ReleaseEventForApiContract webLinks(List<WebLinkForApiContract> webLinks) {
    
    this.webLinks = webLinks;
    return this;
  }

  public ReleaseEventForApiContract addWebLinksItem(WebLinkForApiContract webLinksItem) {
    if (this.webLinks == null) {
      this.webLinks = new ArrayList<>();
    }
    this.webLinks.add(webLinksItem);
    return this;
  }

   /**
   * Get webLinks
   * @return webLinks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WEB_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WebLinkForApiContract> getWebLinks() {
    return webLinks;
  }


  @JsonProperty(JSON_PROPERTY_WEB_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebLinks(List<WebLinkForApiContract> webLinks) {
    this.webLinks = webLinks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReleaseEventForApiContract releaseEventForApiContract = (ReleaseEventForApiContract) o;
    return Objects.equals(this.additionalNames, releaseEventForApiContract.additionalNames) &&
        Objects.equals(this.artists, releaseEventForApiContract.artists) &&
        Objects.equals(this.category, releaseEventForApiContract.category) &&
        Objects.equals(this.date, releaseEventForApiContract.date) &&
        Objects.equals(this.description, releaseEventForApiContract.description) &&
        Objects.equals(this.endDate, releaseEventForApiContract.endDate) &&
        Objects.equals(this.id, releaseEventForApiContract.id) &&
        Objects.equals(this.mainPicture, releaseEventForApiContract.mainPicture) &&
        Objects.equals(this.name, releaseEventForApiContract.name) &&
        Objects.equals(this.names, releaseEventForApiContract.names) &&
        Objects.equals(this.series, releaseEventForApiContract.series) &&
        Objects.equals(this.seriesId, releaseEventForApiContract.seriesId) &&
        Objects.equals(this.seriesNumber, releaseEventForApiContract.seriesNumber) &&
        Objects.equals(this.seriesSuffix, releaseEventForApiContract.seriesSuffix) &&
        Objects.equals(this.songList, releaseEventForApiContract.songList) &&
        Objects.equals(this.status, releaseEventForApiContract.status) &&
        Objects.equals(this.tags, releaseEventForApiContract.tags) &&
        Objects.equals(this.urlSlug, releaseEventForApiContract.urlSlug) &&
        Objects.equals(this.venue, releaseEventForApiContract.venue) &&
        Objects.equals(this.venueName, releaseEventForApiContract.venueName) &&
        Objects.equals(this.version, releaseEventForApiContract.version) &&
        Objects.equals(this.webLinks, releaseEventForApiContract.webLinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalNames, artists, category, date, description, endDate, id, mainPicture, name, names, series, seriesId, seriesNumber, seriesSuffix, songList, status, tags, urlSlug, venue, venueName, version, webLinks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReleaseEventForApiContract {\n");
    sb.append("    additionalNames: ").append(toIndentedString(additionalNames)).append("\n");
    sb.append("    artists: ").append(toIndentedString(artists)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mainPicture: ").append(toIndentedString(mainPicture)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    names: ").append(toIndentedString(names)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    seriesId: ").append(toIndentedString(seriesId)).append("\n");
    sb.append("    seriesNumber: ").append(toIndentedString(seriesNumber)).append("\n");
    sb.append("    seriesSuffix: ").append(toIndentedString(seriesSuffix)).append("\n");
    sb.append("    songList: ").append(toIndentedString(songList)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    urlSlug: ").append(toIndentedString(urlSlug)).append("\n");
    sb.append("    venue: ").append(toIndentedString(venue)).append("\n");
    sb.append("    venueName: ").append(toIndentedString(venueName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    webLinks: ").append(toIndentedString(webLinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

