/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.api;

import mikufan.cx.vocadbapiclient.model.ContentLanguagePreference;
import mikufan.cx.vocadbapiclient.model.PVForSongContractPartialFindResult;
import mikufan.cx.vocadbapiclient.model.PVService;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PvApiApi
 */
@Ignore
public class PvApiApiTest {

    private final PvApiApi api = new PvApiApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiPvsForSongsGetTest() {
        String name = null;
        String author = null;
        PVService service = null;
        Integer maxResults = null;
        Boolean getTotalCount = null;
        ContentLanguagePreference lang = null;
        PVForSongContractPartialFindResult response = api.apiPvsForSongsGet(name, author, service, maxResults, getTotalCount, lang);

        // TODO: test validations
    }
    
}
