/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package mikufan.cx.vocadbapiclient.api;

import mikufan.cx.vocadbapiclient.model.AlbumForApiContract;
import mikufan.cx.vocadbapiclient.model.AlbumOptionalFields;
import mikufan.cx.vocadbapiclient.model.ContentLanguagePreference;
import mikufan.cx.vocadbapiclient.model.EntryStatus;
import mikufan.cx.vocadbapiclient.model.EventCategory;
import mikufan.cx.vocadbapiclient.model.EventReportType;
import mikufan.cx.vocadbapiclient.model.EventSortRule;
import java.time.LocalDateTime;
import mikufan.cx.vocadbapiclient.model.NameMatchMode;
import mikufan.cx.vocadbapiclient.model.ReleaseEventForApiContract;
import mikufan.cx.vocadbapiclient.model.ReleaseEventForApiContractPartialFindResult;
import mikufan.cx.vocadbapiclient.model.ReleaseEventOptionalFields;
import mikufan.cx.vocadbapiclient.model.SongForApiContract;
import mikufan.cx.vocadbapiclient.model.SongOptionalFields;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReleaseEventApiApi
 */
@Ignore
public class ReleaseEventApiApiTest {

    private final ReleaseEventApiApi api = new ReleaseEventApiApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsEventIdAlbumsGetTest() {
        Integer eventId = null;
        AlbumOptionalFields fields = null;
        ContentLanguagePreference lang = null;
        List<AlbumForApiContract> response = api.apiReleaseEventsEventIdAlbumsGet(eventId, fields, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsEventIdPublishedSongsGetTest() {
        Integer eventId = null;
        SongOptionalFields fields = null;
        ContentLanguagePreference lang = null;
        List<SongForApiContract> response = api.apiReleaseEventsEventIdPublishedSongsGet(eventId, fields, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsEventIdReportsPostTest() {
        Integer eventId = null;
        EventReportType reportType = null;
        String notes = null;
        Integer versionNumber = null;
        api.apiReleaseEventsEventIdReportsPost(eventId, reportType, notes, versionNumber);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsGetTest() {
        String query = null;
        NameMatchMode nameMatchMode = null;
        Integer seriesId = null;
        LocalDateTime afterDate = null;
        LocalDateTime beforeDate = null;
        EventCategory category = null;
        Integer userCollectionId = null;
        List<Integer> tagId = null;
        Boolean childTags = null;
        List<Integer> artistId = null;
        Boolean childVoicebanks = null;
        Boolean includeMembers = null;
        EntryStatus status = null;
        Integer start = null;
        Integer maxResults = null;
        Boolean getTotalCount = null;
        EventSortRule sort = null;
        ReleaseEventOptionalFields fields = null;
        ContentLanguagePreference lang = null;
        ReleaseEventForApiContractPartialFindResult response = api.apiReleaseEventsGet(query, nameMatchMode, seriesId, afterDate, beforeDate, category, userCollectionId, tagId, childTags, artistId, childVoicebanks, includeMembers, status, start, maxResults, getTotalCount, sort, fields, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsIdDeleteTest() {
        Integer id = null;
        String notes = null;
        Boolean hardDelete = null;
        api.apiReleaseEventsIdDelete(id, notes, hardDelete);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsIdGetTest() {
        Integer id = null;
        ReleaseEventOptionalFields fields = null;
        ContentLanguagePreference lang = null;
        ReleaseEventForApiContract response = api.apiReleaseEventsIdGet(id, fields, lang);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiReleaseEventsNamesGetTest() {
        String query = null;
        Integer maxResults = null;
        List<String> response = api.apiReleaseEventsNamesGet(query, maxResults);

        // TODO: test validations
    }
    
}
