/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.DiscType;
import cx.mikufan.vocadbapiclient.model.EntryStatus;
import cx.mikufan.vocadbapiclient.model.OptionalDateTimeContract;
import cx.mikufan.vocadbapiclient.model.ReleaseEventForApiContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * AlbumContract
 */
@JsonPropertyOrder({
  AlbumContract.JSON_PROPERTY_ADDITIONAL_NAMES,
  AlbumContract.JSON_PROPERTY_ARTIST_STRING,
  AlbumContract.JSON_PROPERTY_COVER_PICTURE_MIME,
  AlbumContract.JSON_PROPERTY_CREATE_DATE,
  AlbumContract.JSON_PROPERTY_DELETED,
  AlbumContract.JSON_PROPERTY_DISC_TYPE,
  AlbumContract.JSON_PROPERTY_ID,
  AlbumContract.JSON_PROPERTY_NAME,
  AlbumContract.JSON_PROPERTY_RATING_AVERAGE,
  AlbumContract.JSON_PROPERTY_RATING_COUNT,
  AlbumContract.JSON_PROPERTY_RELEASE_DATE,
  AlbumContract.JSON_PROPERTY_RELEASE_EVENT,
  AlbumContract.JSON_PROPERTY_STATUS,
  AlbumContract.JSON_PROPERTY_VERSION
})
@JsonTypeName("AlbumContract")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-20T13:35:02.772911500-04:00[America/New_York]")
public class AlbumContract {
  public static final String JSON_PROPERTY_ADDITIONAL_NAMES = "additionalNames";
  private String additionalNames;

  public static final String JSON_PROPERTY_ARTIST_STRING = "artistString";
  private String artistString;

  public static final String JSON_PROPERTY_COVER_PICTURE_MIME = "coverPictureMime";
  private String coverPictureMime;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  private LocalDateTime createDate;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_DISC_TYPE = "discType";
  private DiscType discType;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_RATING_AVERAGE = "ratingAverage";
  private Double ratingAverage;

  public static final String JSON_PROPERTY_RATING_COUNT = "ratingCount";
  private Integer ratingCount;

  public static final String JSON_PROPERTY_RELEASE_DATE = "releaseDate";
  private OptionalDateTimeContract releaseDate;

  public static final String JSON_PROPERTY_RELEASE_EVENT = "releaseEvent";
  private ReleaseEventForApiContract releaseEvent;

  public static final String JSON_PROPERTY_STATUS = "status";
  private EntryStatus status;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;


  public AlbumContract additionalNames(String additionalNames) {
    
    this.additionalNames = additionalNames;
    return this;
  }

   /**
   * Get additionalNames
   * @return additionalNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalNames() {
    return additionalNames;
  }


  public void setAdditionalNames(String additionalNames) {
    this.additionalNames = additionalNames;
  }


  public AlbumContract artistString(String artistString) {
    
    this.artistString = artistString;
    return this;
  }

   /**
   * Get artistString
   * @return artistString
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ARTIST_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArtistString() {
    return artistString;
  }


  public void setArtistString(String artistString) {
    this.artistString = artistString;
  }


  public AlbumContract coverPictureMime(String coverPictureMime) {
    
    this.coverPictureMime = coverPictureMime;
    return this;
  }

   /**
   * Get coverPictureMime
   * @return coverPictureMime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COVER_PICTURE_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoverPictureMime() {
    return coverPictureMime;
  }


  public void setCoverPictureMime(String coverPictureMime) {
    this.coverPictureMime = coverPictureMime;
  }


  public AlbumContract createDate(LocalDateTime createDate) {
    
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getCreateDate() {
    return createDate;
  }


  public void setCreateDate(LocalDateTime createDate) {
    this.createDate = createDate;
  }


  public AlbumContract deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public AlbumContract discType(DiscType discType) {
    
    this.discType = discType;
    return this;
  }

   /**
   * Get discType
   * @return discType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISC_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DiscType getDiscType() {
    return discType;
  }


  public void setDiscType(DiscType discType) {
    this.discType = discType;
  }


  public AlbumContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public AlbumContract name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public AlbumContract ratingAverage(Double ratingAverage) {
    
    this.ratingAverage = ratingAverage;
    return this;
  }

   /**
   * Get ratingAverage
   * @return ratingAverage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RATING_AVERAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRatingAverage() {
    return ratingAverage;
  }


  public void setRatingAverage(Double ratingAverage) {
    this.ratingAverage = ratingAverage;
  }


  public AlbumContract ratingCount(Integer ratingCount) {
    
    this.ratingCount = ratingCount;
    return this;
  }

   /**
   * Get ratingCount
   * @return ratingCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RATING_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRatingCount() {
    return ratingCount;
  }


  public void setRatingCount(Integer ratingCount) {
    this.ratingCount = ratingCount;
  }


  public AlbumContract releaseDate(OptionalDateTimeContract releaseDate) {
    
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OptionalDateTimeContract getReleaseDate() {
    return releaseDate;
  }


  public void setReleaseDate(OptionalDateTimeContract releaseDate) {
    this.releaseDate = releaseDate;
  }


  public AlbumContract releaseEvent(ReleaseEventForApiContract releaseEvent) {
    
    this.releaseEvent = releaseEvent;
    return this;
  }

   /**
   * Get releaseEvent
   * @return releaseEvent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELEASE_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReleaseEventForApiContract getReleaseEvent() {
    return releaseEvent;
  }


  public void setReleaseEvent(ReleaseEventForApiContract releaseEvent) {
    this.releaseEvent = releaseEvent;
  }


  public AlbumContract status(EntryStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryStatus getStatus() {
    return status;
  }


  public void setStatus(EntryStatus status) {
    this.status = status;
  }


  public AlbumContract version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlbumContract albumContract = (AlbumContract) o;
    return Objects.equals(this.additionalNames, albumContract.additionalNames) &&
        Objects.equals(this.artistString, albumContract.artistString) &&
        Objects.equals(this.coverPictureMime, albumContract.coverPictureMime) &&
        Objects.equals(this.createDate, albumContract.createDate) &&
        Objects.equals(this.deleted, albumContract.deleted) &&
        Objects.equals(this.discType, albumContract.discType) &&
        Objects.equals(this.id, albumContract.id) &&
        Objects.equals(this.name, albumContract.name) &&
        Objects.equals(this.ratingAverage, albumContract.ratingAverage) &&
        Objects.equals(this.ratingCount, albumContract.ratingCount) &&
        Objects.equals(this.releaseDate, albumContract.releaseDate) &&
        Objects.equals(this.releaseEvent, albumContract.releaseEvent) &&
        Objects.equals(this.status, albumContract.status) &&
        Objects.equals(this.version, albumContract.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalNames, artistString, coverPictureMime, createDate, deleted, discType, id, name, ratingAverage, ratingCount, releaseDate, releaseEvent, status, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlbumContract {\n");
    sb.append("    additionalNames: ").append(toIndentedString(additionalNames)).append("\n");
    sb.append("    artistString: ").append(toIndentedString(artistString)).append("\n");
    sb.append("    coverPictureMime: ").append(toIndentedString(coverPictureMime)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    discType: ").append(toIndentedString(discType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ratingAverage: ").append(toIndentedString(ratingAverage)).append("\n");
    sb.append("    ratingCount: ").append(toIndentedString(ratingCount)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    releaseEvent: ").append(toIndentedString(releaseEvent)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

