/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ArchivedObjectVersionForApiContract
 */
@JsonPropertyOrder({
  ArchivedObjectVersionForApiContract.JSON_PROPERTY_CHANGED_FIELDS,
  ArchivedObjectVersionForApiContract.JSON_PROPERTY_ID,
  ArchivedObjectVersionForApiContract.JSON_PROPERTY_NOTES,
  ArchivedObjectVersionForApiContract.JSON_PROPERTY_VERSION
})
@JsonTypeName("ArchivedObjectVersionForApiContract")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-20T13:35:02.772911500-04:00[America/New_York]")
public class ArchivedObjectVersionForApiContract {
  public static final String JSON_PROPERTY_CHANGED_FIELDS = "changedFields";
  private List<String> changedFields = null;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NOTES = "notes";
  private String notes;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;


  public ArchivedObjectVersionForApiContract changedFields(List<String> changedFields) {
    
    this.changedFields = changedFields;
    return this;
  }

  public ArchivedObjectVersionForApiContract addChangedFieldsItem(String changedFieldsItem) {
    if (this.changedFields == null) {
      this.changedFields = new ArrayList<>();
    }
    this.changedFields.add(changedFieldsItem);
    return this;
  }

   /**
   * Get changedFields
   * @return changedFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHANGED_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getChangedFields() {
    return changedFields;
  }


  public void setChangedFields(List<String> changedFields) {
    this.changedFields = changedFields;
  }


  public ArchivedObjectVersionForApiContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public ArchivedObjectVersionForApiContract notes(String notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNotes() {
    return notes;
  }


  public void setNotes(String notes) {
    this.notes = notes;
  }


  public ArchivedObjectVersionForApiContract version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchivedObjectVersionForApiContract archivedObjectVersionForApiContract = (ArchivedObjectVersionForApiContract) o;
    return Objects.equals(this.changedFields, archivedObjectVersionForApiContract.changedFields) &&
        Objects.equals(this.id, archivedObjectVersionForApiContract.id) &&
        Objects.equals(this.notes, archivedObjectVersionForApiContract.notes) &&
        Objects.equals(this.version, archivedObjectVersionForApiContract.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedFields, id, notes, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchivedObjectVersionForApiContract {\n");
    sb.append("    changedFields: ").append(toIndentedString(changedFields)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

