/*
 * VocaDbWeb
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cx.mikufan.vocadbapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import cx.mikufan.vocadbapiclient.model.ArtistType;
import cx.mikufan.vocadbapiclient.model.EntryStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ArtistContract
 */
@JsonPropertyOrder({
  ArtistContract.JSON_PROPERTY_ADDITIONAL_NAMES,
  ArtistContract.JSON_PROPERTY_ARTIST_TYPE,
  ArtistContract.JSON_PROPERTY_DELETED,
  ArtistContract.JSON_PROPERTY_ID,
  ArtistContract.JSON_PROPERTY_NAME,
  ArtistContract.JSON_PROPERTY_PICTURE_MIME,
  ArtistContract.JSON_PROPERTY_RELEASE_DATE,
  ArtistContract.JSON_PROPERTY_STATUS,
  ArtistContract.JSON_PROPERTY_VERSION
})
@JsonTypeName("ArtistContract")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-20T13:35:02.772911500-04:00[America/New_York]")
public class ArtistContract {
  public static final String JSON_PROPERTY_ADDITIONAL_NAMES = "additionalNames";
  private String additionalNames;

  public static final String JSON_PROPERTY_ARTIST_TYPE = "artistType";
  private ArtistType artistType;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  private Boolean deleted;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PICTURE_MIME = "pictureMime";
  private String pictureMime;

  public static final String JSON_PROPERTY_RELEASE_DATE = "releaseDate";
  private LocalDateTime releaseDate;

  public static final String JSON_PROPERTY_STATUS = "status";
  private EntryStatus status;

  public static final String JSON_PROPERTY_VERSION = "version";
  private Integer version;


  public ArtistContract additionalNames(String additionalNames) {
    
    this.additionalNames = additionalNames;
    return this;
  }

   /**
   * Get additionalNames
   * @return additionalNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdditionalNames() {
    return additionalNames;
  }


  public void setAdditionalNames(String additionalNames) {
    this.additionalNames = additionalNames;
  }


  public ArtistContract artistType(ArtistType artistType) {
    
    this.artistType = artistType;
    return this;
  }

   /**
   * Get artistType
   * @return artistType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ARTIST_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ArtistType getArtistType() {
    return artistType;
  }


  public void setArtistType(ArtistType artistType) {
    this.artistType = artistType;
  }


  public ArtistContract deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public ArtistContract id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public ArtistContract name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ArtistContract pictureMime(String pictureMime) {
    
    this.pictureMime = pictureMime;
    return this;
  }

   /**
   * Get pictureMime
   * @return pictureMime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PICTURE_MIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPictureMime() {
    return pictureMime;
  }


  public void setPictureMime(String pictureMime) {
    this.pictureMime = pictureMime;
  }


  public ArtistContract releaseDate(LocalDateTime releaseDate) {
    
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RELEASE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getReleaseDate() {
    return releaseDate;
  }


  public void setReleaseDate(LocalDateTime releaseDate) {
    this.releaseDate = releaseDate;
  }


  public ArtistContract status(EntryStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntryStatus getStatus() {
    return status;
  }


  public void setStatus(EntryStatus status) {
    this.status = status;
  }


  public ArtistContract version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtistContract artistContract = (ArtistContract) o;
    return Objects.equals(this.additionalNames, artistContract.additionalNames) &&
        Objects.equals(this.artistType, artistContract.artistType) &&
        Objects.equals(this.deleted, artistContract.deleted) &&
        Objects.equals(this.id, artistContract.id) &&
        Objects.equals(this.name, artistContract.name) &&
        Objects.equals(this.pictureMime, artistContract.pictureMime) &&
        Objects.equals(this.releaseDate, artistContract.releaseDate) &&
        Objects.equals(this.status, artistContract.status) &&
        Objects.equals(this.version, artistContract.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalNames, artistType, deleted, id, name, pictureMime, releaseDate, status, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtistContract {\n");
    sb.append("    additionalNames: ").append(toIndentedString(additionalNames)).append("\n");
    sb.append("    artistType: ").append(toIndentedString(artistType)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pictureMime: ").append(toIndentedString(pictureMime)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

